spring:
  datasource:
    url: jdbc:h2:file:./data/audio-editor-db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: ""
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

server:
  port: 8080

storage:
  root: ${user.dir}/storage
  uploadsDir: ${user.dir}/storage/uploads
  exportsDir: ${user.dir}/storage/exports
  wavDir: ${user.dir}/storage/wav

ffmpeg:
  path: ffmpeg
