package com.ivanka.audioeditor.client.core.events;

public enum EditorEventType {
    PROJECT_CREATE_REQUEST,
    PROJECT_CREATED,
    PROJECT_SELECTED,
    TRACK_ADD_REQUEST,
    TRACK_ADDED,
    IMPORT_REQUEST,
    AUDIO_IMPORTED,
    EXPORT_REQUEST,
    EXPORT_FINISHED,
    CLIPBOARD_COPY,
    CLIPBOARD_CUT,
    CLIPBOARD_PASTE,
    PLAYBACK_START,
    PLAYBACK_STOP,
    WAVEFORM_REDRAW,
    TRACKS_REFRESH_REQUEST,
    NOTIFY_INFO,
    NOTIFY_WARN,
    NOTIFY_ERROR ,
    }
